version: "3.9"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"